pull_request_rules:
- actions:
    comment:
      message: Hello!
  conditions:
  - base=20220624071835/test_label_basic/main
  name: hello
- actions:
    assign:
      users:
      - mergify-test1
    label:
      add:
      - need-review
      remove:
      - auto-merge
    merge: {}
  conditions:
  - base=20220624071835/test_label_basic/main
  name: mergeit
