priority_rules:
- conditions:
  - label=urgent
  name: high priority
  priority: high
pull_request_rules:
- actions:
    queue: {}
  conditions:
  - base=20250509214948/test_pull_request_implicitly_merged/main
  name: default merge
queue_rules:
- name: default
