pull_request_rules:
- actions:
    comment:
      message: Only this one please
  conditions:
  - base=20230222112147/test_head_template_attribute/main
  name: match
- actions:
    comment:
      message: no way
  conditions:
  - base=20230222112147/test_head_template_attribute/main
  - -head~=^{{ author }}
  name: don't match
