pull_request_rules:
- actions:
    review:
      type: APPROVE
  conditions:
  - base=20220524122436/test_request_reviews_already_max/main
  name: approve
- actions:
    request_reviews:
      users:
      - mergify-test1
      - mergify-test
  conditions:
  - base=20220524122436/test_request_reviews_already_max/main
  name: request_reviews
