pull_request_rules:
- actions:
    merge:
      priority: high
  conditions:
  - base=20221216155455/test_merge_priority_deprecation_notice/main
  - label=high
  - status-success=continuous-integration/fake-ci
  name: Merge priority high
