pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20230803111519/test_batch_bug_github_issue/main
  - label=queue
  name: default merge
queue_rules:
- allow_inplace_checks: true
  batch_max_wait_time: 3 s
  batch_size: 2
  conditions:
  - status-success=continuous-integration/fake-ci
  name: default
  speculative_checks: 1
