pull_request_rules:
- actions:
    copy:
      regexes:
      - whatever-that-will-never-ever-match
  conditions:
  - base=20250220221247/test_copy_with_no_matching_branch/main
  - label=backport-#3.1
  name: copy
