pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20230124205942/test_unqueue_rule_unmatches/main
  - label=queue
  name: Merge priority high
queue_rules:
- allow_inplace_checks: true
  conditions:
  - status-success=continuous-integration/fake-ci
  name: default
