pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20230223210950/test_queue_routing_conditions_failure/main
  - label=queue
  name: Queue
queue_rules:
- merge_conditions:
  - status-success=continuous-integration/fake-ci
  name: default
  routing_conditions:
  - files~=^dummy/
