pull_request_rules: 
  - name: "hello"
    conditions: 
    - base=main
    - label=auto-merge
    actions:
      comment:
        message: "Hello!"
 
  - name: "merge<h1>it</h1>"
    conditions:
    - base=main
    actions:
      assign:
        users: ["mergify-test1"]
      label: 
        add: ["need-review"]
        remove: ["auto-<b>merge</b>"]
      merge:
