pull_request_rules:
- actions:
    queue:
      name: default
      update_bot_account: '{% if 1 -%}mergify-test4{% endif -%}'
      update_method: rebase
  conditions:
  - base=20250316215726/test_queue_with_rebase_update_method/main
  - label=queue
  name: default merge
queue_rules:
- autosquash: true
  conditions:
  - status-success=continuous-integration/fake-ci
  name: default
