pull_request_rules:
- actions:
    review:
      type: APPROVE
  conditions:
  - base=20220524123850/test_review_with_oauth_token/main
  name: approve
- actions:
    review:
      bot_account: mergify-test4
      message: WTF?
      type: REQUEST_CHANGES
  conditions:
  - base=20220524123850/test_review_with_oauth_token/main
  name: requested
