pull_request_rules:
- actions:
    update: {}
  conditions:
  - base=20220923143119/test_update_action/main
  name: update
- actions:
    merge: {}
  conditions:
  - base=20220923143119/test_update_action/main
  - label=merge
  name: merge
