pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20250916122848/test_report_error_bot_account_wrong_permissions/main
  - label=queue
  name: Merge default
queue_rules:
- merge_bot_account: mergify-test2
  merge_conditions:
  - status-success=continuous-integration/fake-ci-merge
  name: default
  queue_conditions:
  - status-success=continuous-integration/fake-ci-queue
