merge_queue:
  max_parallel_checks: 5
pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20250401114439/test_queue_rule_deleted/main
  name: Merge me
queue_rules:
- allow_inplace_checks: true
  conditions:
  - status-success=continuous-integration/fake-ci
  name: default
