merge_queue:
  max_parallel_checks: 1
pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20250916172738/test_unqueue_compat/main
  name: Queue
queue_rules:
- conditions:
  - status-success=continuous-integration/fake-ci
  name: default
