pull_request_rules:
- actions:
    merge:
      allow_merging_configuration_change: true
  conditions:
  - base=20230331090458/test_allowed_change_mergify_yml/main
  name: nothing
- actions:
    merge: {}
  conditions:
  - label!=wip
  name: foobar
