pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20250916174507/test_strict_status_check/main
  name: Update and Merge
queue_rules:
- merge_conditions:
  - label=merge
  merge_method: squash
  name: default
  queue_conditions:
  - label=queue
