pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - label=queue
  name: default merge
queue_rules:
- name: default
  queue_conditions:
  - base=20250312074606/test_merging_a_stack/main
