pull_request_rules:
- actions:
    queue: {}
  conditions:
  - base=20230223171534/test_queue_priority_deprecation_notice_not_present_in_summary/main
  - label=high
  - status-success=continuous-integration/fake-ci
  name: Merge priority high
