pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20221221121510/test_queue_inplace_train_resetted/main
  - check-success=pr-ci
  name: Merge priority high
queue_rules:
- conditions:
  - check-success=queue-ci
  name: default
