pull_request_rules:
- actions:
    dismiss_reviews:
      approved: from_requested_reviewers
      when: always
  conditions:
  - base=20250307065534/test_dismiss_reviews_from_requested_reviewers/main
  name: dismiss reviews
