merge_queue:
  max_parallel_checks: 1
pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20250916133828/test_queue_cancel_and_refresh_inplace/main
  - status-success=continuous-integration/fake-ci
  name: Tchou tchou
queue_rules:
- allow_inplace_checks: true
  conditions:
  - status-success=continuous-integration/fake-ci
  name: default
