pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20221221112742/test_queue_inplace_train_resetted/main
  - continuous-integration/fake-ci
  name: Merge priority high
queue_rules:
- conditions:
  - continuous-integration/fake-ci
  name: default
