pull_request_rules:
- actions:
    github_actions:
      workflow:
        dispatch:
        - ref: 20250227114027/test_gha_workflow_no_dispatch/main
          workflow: no_dispatch_workflow.yaml
  conditions:
  - label=dispatch
  name: Dispatch GHA
