pull_request_rules:
- actions:
    merge:
      merge_bot_account: '{{ body }}'
      method: fast-forward
  conditions:
  - base=20220826095650/test_merge_fastforward_bot_account/main
  name: merge on main
