pull_request_rules:
- actions:
    queue:
      name: urgent
  conditions:
  - base=20230317161725/test_queue_priority/main
  - label=queue-urgent
  name: Merge priority high urgent
- actions:
    queue:
      name: default
  conditions:
  - base=20230317161725/test_queue_priority/main
  - label=queue
  name: Merge priority high default
queue_rules:
- allow_inplace_checks: false
  conditions:
  - status-success=continuous-integration/fast-ci
  name: urgent
  speculative_checks: 5
- allow_inplace_checks: false
  conditions:
  - status-success=continuous-integration/slow-ci
  name: default
  speculative_checks: 5
