merge_queue:
  max_parallel_checks: 1
pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20250916140208/test_queue_inplace_with_merge_update_method_without_bot_account/main
  - label=queue
  name: merge default
queue_rules:
- conditions:
  - status-success=continuous-integration/fake-ci
  name: default
  update_method: merge
