merge_queue:
  max_parallel_checks: 1
pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20250916140426/test_queue_just_rebase/main
  - label=queue
  name: default merge
queue_rules:
- conditions:
  - label=queue
  name: default
