pull_request_rules:
- actions:
    merge:
      method: squash
  conditions:
  - base=20250402205256/test_merge_custom_msg_rn/main
  - status-success=continuous-integration/fake-ci
  name: Merge on main
