defaults:
  actions:
    queue:
      name: default
      method: squash
      update_method: rebase
queue_rules:
  - name: default
    conditions:
      - label=merge
 
pull_request_rules: 
  - name: automatic merge
    conditions:
      - base=main
      - label=merge
    actions:
      queue:
      
  - name: is it merged?
    conditions:
      - merged
    actions:
      post_check:
        title: |
          {% if check_succeed %}
          It's merged
          {% else %}
          It's not merged...
          {% endif %}
