pull_request_rules:
- actions:
    label:
      add:
      - unstable
      - foobar
      - vEcToR
      remove:
      - stable
      - what
      - ReMoVe-Me
  conditions:
  - base=20250916121630/test_label_basic/main
  name: rename label
