merge_queue:
  max_parallel_checks: 1
pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20250916131518/test_more_ci_in_pull_request_rules_succeed/main
  - status-success=continuous-integration/fake-ci
  - status-success=very-long-ci
  - label=queue
  name: default merge
queue_rules:
- conditions:
  - status-success=continuous-integration/fake-ci
  name: default
