pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20250221073015/test_unqueue_command_after_queue_action_and_command/main
  - label=queue
  name: Merge on queue label
queue_rules:
- conditions: []
  name: default
