merge_queue:
  max_parallel_checks: 1
pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20250916135239/test_queue_fast_forward_with_retries/main
  - label=queue
  name: merge fast-forward
queue_rules:
- merge_conditions:
  - status-success=continuous-integration/fake-ci
  merge_method: fast-forward
  name: default
