merge_queue:
  max_parallel_checks: 5
pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20250307081327/test_queue_rule_deleted/main
  - label=automerge
  name: Merge only if label is present
queue_rules:
- allow_inplace_checks: false
  conditions:
  - status-success=continuous-integration/fake-ci
  name: default
