pull_request_rules: 
  - name: "hello"
    conditions: 
    - base=main
    - label=auto-merge
    actions:
      comment:
        message: "Hello!"
 
  - name: "mergeit"
    conditions:
    - base=main
    actions:
      assign:
        users: ["mergify-test1"]
      label: 
        add: ["need-review"]
        remove: ["auto-merge"]
      merge: