pull_request_rules:
- actions:
    merge:
      method: merge
      rebase_fallback: null
  conditions:
  - base=20210920144050/test_backport_with_bot_account/main
  - label=backport-#3.1
  name: Merge on main
- actions:
    backport:
      bot_account: mergify-test3
      branches:
      - 20210920144050/test_backport_with_bot_account/stable/#3.1
  conditions:
  - base=20210920144050/test_backport_with_bot_account/main
  - label=backport-#3.1
  name: Backport to stable/#3.1
