pull_request_rules:
- actions:
    queue:
      method: fast-forward
      name: default
      priority: high
  conditions:
  - base=20220513213725/test_speculative_checks_fastforward/main
  - label=queue
  name: Merge priority high
queue_rules:
- batch_size: 2
  conditions:
  - status-success=continuous-integration/fake-ci
  name: default
  speculative_checks: 2
