pull_request_rules:
- actions:
    rebase:
      autosquash: true
      bot_account: mergify-test2
  conditions:
  - base=20230307110025/test_rebase_autosquash_squash_commit/main
  - label=rebase
  name: rebase
