pull_request_rules:
- actions:
    comment:
      message: review-requested user
  conditions:
  - base=20210824145143/test_requested_reviews/main
  - review-requested=mergify-test3
  name: user
- actions:
    comment:
      message: review-requested team
  conditions:
  - base=20210824145143/test_requested_reviews/main
  - review-requested=@testing
  name: team
