pull_request_rules:
- actions:
    merge:
      method: squash
  conditions:
  - base=20250311210428/test_merge_custom_msg/main
  - status-success=continuous-integration/fake-ci
  name: Merge on main
