pull_request_rules:
- actions:
    merge: {}
  conditions:
  - base=20250402234042/test_disallowed_change_mergify_yml/main
  - -mergify-configuration-changed
  name: nothing
- actions:
    merge: {}
  conditions:
  - label!=wip
  name: foobar
