pull_request_rules:
- actions:
    merge: {}
  conditions:
  - base=20230307105443/test_rebase_fallback_deprecation_notice_not_present_in_summary/main
  - label=high
  - status-success=continuous-integration/fake-ci
  name: Merge priority high
