pull_request_rules:
- actions:
    update: {}
  conditions:
  - base=20250725083606/test_update_action_on_conflict/main
  name: update
- actions:
    merge: {}
  conditions:
  - base=20250725083606/test_update_action_on_conflict/main
  - label=merge
  name: merge
