pull_request_rules:
- actions:
    merge:
      priority: high
      strict: smart+ordered
  conditions:
  - base=20211007064556/test_merge_rule_switch/main
  - label=high
  - status-success=continuous-integration/fake-ci
  name: Merge priority high
- actions:
    merge:
      strict: smart+ordered
  conditions:
  - base=20211007064556/test_merge_rule_switch/main
  - label=medium
  - status-success=continuous-integration/fake-ci
  name: Merge priority medium
- actions:
    merge:
      priority: 1
      strict: smart+ordered
  conditions:
  - base=20211007064556/test_merge_rule_switch/main
  - label=low
  - status-success=continuous-integration/fake-ci
  name: Merge priority low
