merge_queue:
  max_parallel_checks: 1
pull_request_rules:
- actions:
    queue: {}
  conditions:
  - label=queue
  name: automatic merge
queue_rules:
- allow_inplace_checks: true
  merge_conditions:
  - status-success=continuous-integration/fake-ci
  name: default
  update_bot_account: mergify-test4
  update_method: rebase
