pull_request_rules:
- actions:
    queue:
      name: default
      update_bot_account: mergify-test4
      update_method: rebase
  conditions:
  - base=20250317084950/test_queue_inplace_uptodate_autosquash_true/main
  - label=queue
  name: Automatic merge
queue_rules:
- allow_inplace_checks: true
  autosquash: true
  conditions:
  - status-success=continuous-integration/fake-ci
  name: default
