pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20221014060956/test_queue_rules_order_0_depth/main
  name: test
queue_rules:
- allow_inplace_checks: false
  batch_size: 2
  conditions:
  - check-success=CI1
  - check-success=CI2
  - base=20221014060956/test_queue_rules_order_0_depth/main
  - label=test
  name: default
  speculative_checks: 2
