pull_request_rules:
- actions:
    github_actions:
      workflow:
        dispatch:
        - inputs:
            author: '{{author}}'
          ref: 20250916121525/test_gha_with_template_input/main
          workflow: dynamic_workflow.yaml
  conditions:
  - label=dispatch
  name: Dispatch GHA
