pull_request_rules:
- actions:
    queue:
      name: default
      priority: high
  conditions:
  - base=20211022062332/test_queue_no_inplace/main
  - label=queue
  name: Merge priority high
queue_rules:
- allow_inplace_speculative_checks: false
  conditions:
  - status-success=continuous-integration/fake-ci
  name: default
  speculative_checks: 5
