pull_request_rules:
- actions:
    queue:
      name: default
      update_bot_account: mergify-test4
      update_method: merge
  conditions:
  - base=20250307174655/test_queue_inplace_with_merge_update_method_and_different_bot_account/main
  - label=queue
  name: merge default
queue_rules:
- conditions: []
  name: default
