pull_request_rules:
- actions:
    merge:
      commit_message_template: '{{ title }} (#{{ number }})

        {{body}}

        superRP!

        '
  conditions:
  - base=20220706081848/test_merge_template/main
  name: merge on main
