pull_request_rules:
- actions:
    queue:
      name: foo
  conditions:
  - base=20231018123401/test_pr_in_queue_without_partitions/main
  - label=queue
  name: queue
queue_rules:
- allow_inplace_checks: false
  merge_conditions:
  - base=20231018123401/test_pr_in_queue_without_partitions/main
  - check-success=continuous-integration/fake-ci
  name: foo
