merge_queue:
  max_parallel_checks: 1
pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - label=queue
  name: default merge
queue_rules:
- merge_conditions:
  - or:
    - status-success=continuous-integration/fake-ci
    - label=merge
  name: default
