pull_request_rules:
- actions:
    merge: !!set
      allow_merging_configuration_change: null
  conditions:
  - base!=20230215133148/test_allowed_change_mergify_yml/main
  name: nothing
- actions:
    merge: {}
  conditions:
  - label!=wip
  name: foobar
