pull_request_rules:
- actions:
    rebase:
      bot_account: mergify-test2
  conditions:
  - base=20230307110552/test_rebase_on_uptodate_pr_branch/main
  - label=rebase
  name: rebase
- actions:
    delete_head_branch: {}
    merge: {}
  conditions:
  - base=20230307110552/test_rebase_on_uptodate_pr_branch/main
  - label=merge
  name: merge
- actions:
    update: {}
  conditions:
  - base=20230307110552/test_rebase_on_uptodate_pr_branch/main
  - label=update
  name: update
