pull_request_rules:
- actions:
    post_check: !!set
      success_conditions=20250309131932/test_refresh_via_check_suite_rerequest/main: null
  conditions:
  - base=20250309131932/test_refresh_via_check_suite_rerequest/main
  name: body-changed
