pull_request_rules:
- actions:
    merge:
      strict: smart
  conditions:
  - base=20211012075656/test_merge_failure_smart_strict/main
  - status-success=continuous-integration/fake-ci
  name: strict merge on main
