pull_request_rules:
- actions:
    merge:
      bot_account: not-exists
      strict: true
      strict_method: rebase
  conditions:
  - base=20210824145244/test_merge_strict_rebase_with_invalid_user/main
  - status-success=continuous-integration/fake-ci
  - '#approved-reviews-by>=1'
  name: smart strict merge on main
