pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20231018114015/test_unfreeze_outside_schedule/main
  - label=queue
  name: queue
queue_rules:
- conditions:
  - 'schedule: MON-FRI 08:00-17:00'
  name: default
