pull_request_rules:
- actions:
    label:
      toggle:
      - CI:fail
  conditions:
  - base=20240701172700/test_label_toggle/main
  - check-failure=continuous-integration/fake-ci
  name: toggle labels
