merge_queue:
  max_parallel_checks: 5
pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20250401113046/test_queue_ci_failure/main
  - label=queue
  name: merge default
queue_rules:
- conditions:
  - status-success=continuous-integration/fake-ci
  name: default
