pull_request_rules:
- actions:
    queue:
      priority: high
  conditions:
  - base=20230317162501/test_queue_priority_deprecation_notice/main
  - label=high
  - status-success=continuous-integration/fake-ci
  name: Merge priority high
