pull_request_rules:
- actions:
    queue: {}
  conditions:
  - label=queue
  name: Queue
queue_rules:
- name: hotfix
  routing_conditions:
  - label=hotfix
- name: default
  routing_conditions:
  - check-success=check
