pull_request_rules:
- actions:
    queue:
      merge_method: squash
      name: default
  conditions:
  - base=20250307175336/test_queue_without_branch_protection_for_queueing/main
  - label=queue
  name: Merge priority high
queue_rules:
- branch_protection_injection_mode: merge
  conditions: []
  name: default
