merge_queue:
  max_parallel_checks: 1
pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - check-success=continuous-integration/fake-ci
  - base=20250807193503/test_queue_auto_reembark/main
  name: Queue
queue_rules:
- name: default
  queue_conditions:
  - check-success=second-ci
