pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20220708190655/test_queue_with_ci_and_files/main
  - label=queue
  name: Queue
queue_rules:
- allow_inplace_checks: false
  conditions:
  - or: !!set
      files=^.*\.rst$: null
      status-success=continuous-integration/fake-ci: null
  name: default
