pull_request_rules:
- actions:
    update: {}
  conditions:
  - base=20250307090957/test_update_action_without_bot/main
  name: update
- actions:
    merge: {}
  conditions:
  - base=20250307090957/test_update_action_without_bot/main
  - label=merge
  name: merge
