defaults:
  actions:
    comment:
      message: Hello World!
pull_request_rules:
- actions:
    comment: null
  conditions:
  - base=20230223201707/test_comment_none_with_default/main
  name: comment without default message
