pull_request_rules:
- actions:
    comment:
      message: and or pr
  conditions:
  - or:
    - and:
      - base=20230223195518/test_and_or/main
      - closed
      - label=foo
    - merged
    - not:
        and:
        - label=foo
        - label=bar
  name: no-draft
