pull_request_rules:
- actions:
    post_check:
      success_conditions:
      - '#title>10'
      - '#title<50'
      - '#body<4096'
      - '#files<100'
      - body~=(?m)^(Fixes|Related|Closes) (MERGIFY-ENGINE|MRGFY)-
      - -label=ignore-guideline
  conditions:
  - base=20220725112501/test_checks_with_conditions/main
  name: body need sentry ticket
