
shared:
  merge_ci: &common_checks
    - "check-success=ci/circleci: check_if_tests_done"
    - "#approved-reviews-by>=1"

merge_queue:
    max_parallel_checks: 1

queue_rules:
  - name: master_queue
    conditions: *common_checks
    checks_timeout: 25m
    merge_method: squash


pull_request_rules:
  - name: master
    conditions:
      - base=20250916140304/test_queue_inplace_with_outdated_pull_request_from_github/main
      - label=to-be-merged
      - and: *common_checks
    actions:
      queue:
        name: master_queue
