partition_rules:
- fallback_partition: true
  name: fallback_partition
- conditions:
  - label=queue
  name: projA
pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20250227164620/test_no_partition_reset_when_pr_manual_merge/main
  - label=queue
  name: Automatic merge
queue_rules:
- allow_inplace_checks: true
  merge_conditions:
  - status-success=continuous-integration/fake-ci
  name: default
