merge_queue:
  max_parallel_checks: 5
pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20250220213153/test_queue_manual_merge/main
  - label=queue
  name: merge default
queue_rules:
- conditions:
  - status-success=continuous-integration/fake-ci
  name: default
