pull_request_rules:
- actions:
    github_actions:
      workflow:
        dispatch:
        - ref: 20250402204733/test_gha_dispatch_forbidden/main
          workflow: workflow_dispatch_forbidden.yaml
  conditions:
  - label=dispatch
  name: Dispatch GHA
