pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20230206183244/test_queue_priority_rules/main
  - label=queue
  name: Merge priority high
queue_rules:
- conditions:
  - status-success=continuous-integration/fake-ci
  name: default
  priority_rules:
  - batch_size: 2
    conditions:
    - label=hotfix
    name: hotfix PR detected
    priority: high
  - conditions:
    - -label=hotfix
    - -label=low
    name: default priority
    priority: medium
  - conditions:
    - label=low
    name: default priority
    priority: low
