pull_request_rules:
- actions:
    merge:
      method: rebase
  conditions:
  - base=20220829135218/test_pull_request_rules_order_operator_and/main
  - label=test
  - and:
    - label=test2
    - label=test3
  name: test
