pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20250403060459/test_unqueue_compat/main
  name: Queue
queue_rules:
- conditions:
  - status-success=continuous-integration/fake-ci
  name: default
