pull_request_rules:
- actions:
    queue:
      name: default
      priority: high
  conditions:
  - status-success=continuous-integration/fake-ci
  - base=20231006054753/test_queue_auto_reembark/main
  name: Merge priority high
queue_rules:
- conditions:
  - check-success=second-ci
  name: default
  speculative_checks: 1
