merge_queue:
  max_parallel_checks: 1
pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20250927215604/test_queue_inplace_train_resetted/main
  - check-success=continuous-integration/fake-ci
  - -conflict
  name: Merge priority high
queue_rules:
- name: default
  queue_conditions:
  - check-success=continuous-integration/fake-ci
