pull_request_rules:
- actions:
    queue:
      name: default
      update_bot_account: mergify-test4
      update_method: rebase
  conditions:
  - base=20250307080440/test_queue_inplace_uptodate_autosquash_false/main
  - label=queue
  name: Automatic merge
queue_rules:
- allow_inplace_checks: true
  autosquash: false
  conditions: []
  name: default
