pull_request_rules:
- actions:
    queue:
      name: default
      priority: high
  conditions:
  - base=20230112222402/test_two_queue_rules_match/main
  - label=high
  name: Merge priority high
- actions:
    queue:
      name: default
      priority: low
  conditions:
  - base=20230112222402/test_two_queue_rules_match/main
  - label=low
  name: Merge priority low
queue_rules:
- allow_inplace_checks: false
  conditions:
  - status-success=continuous-integration/fake-ci
  name: default
