pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20231105191258/test_queue_conditions_failure_update_after_queued/main
  - label=queue
  name: Queue
queue_rules:
- merge_conditions:
  - status-success=continuous-integration/fake-ci
  name: default
  queue_conditions:
  - label=routing
