pull_request_rules:
- actions:
    backport:
      branches:
      - 20240311134517/TBAtest_backport_close/stable/#3.1
  conditions:
  - base=20240311134517/TBAtest_backport_close/main
  - label=backport-#3.1
  name: Backport to stable/#3.1
