pull_request_rules:
- actions:
    merge:
      strict: true
      strict_method: rebase
      update_bot_account: not-exists
  conditions:
  - base=20210902140609/test_merge_strict_rebase_with_invalid_user/main
  - status-success=continuous-integration/fake-ci
  - '#approved-reviews-by>=1'
  name: smart strict merge on main
