jobs:
  test-dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Workflow missing dispatch trigger
      run: echo yolo
name: no_dispatch
'on':
  pull_request:
    branches: 20250308094805/test_gha_workflow_no_dispatch/main
