jobs:
  test-dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Test dispatched workflow inputs
      run: echo fails anyway
name: workflow_run_forbidden
'on':
  pull_request:
    branches: 20250220221314/test_gha_dispatch_forbidden/main
  workflow_dispatch:
    inputs: {}
